controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_dashboard:
    path: /
    controller: App\Controller\DashboardController::index
    methods: GET

app_entreprise:
    path: /entreprise
    controller: App\Controller\EntrepriseController::index
    methods: GET

app_employe:
    path: /employe
    controller: App\Controller\EmployeController::index
    methods: GET

app_etudiant:
    path: /etudiant
    controller: App\Controller\EtudiantController::index
    methods: GET

app_stage:
    path: /stage
    controller: App\Controller\StageController::index
    methods: GET

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index
    methods: GET

app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_register:
    path: /register
    controller: App\Controller\AuthController::register

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
