controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_dashboard:
    path: /
    controller: App\Controller\DashboardController::index

app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
